# Esercizi con Numpy

## 1. Array inversi [[Esercizio su HackerRank](https://www.hackerrank.com/challenges/np-arrays/problem)]
Acquisici in input una lista di numeri, definisci una funzione per creare un'array numpy di float partendo dalla lista con l'ordine degli elementi invertito.
<br><br>
**Esempio di input**<br>
1 2 3 4 -8 -10
<br><br>
**Esempio di output**<br>
[-10.  -8.   4.   3.   2.   1.]

In [2]:
import numpy as np

def arrays(arr):
    # numpy.array(arr, float)[::-1]
    np_arr = np.array(arr, float)
    np_arr = np_arr[::-1]
    return np_arr


arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5
[5. 4. 3. 2. 1.]


## 2. Shape e Reshape [[Esercizio su HackerRank](https://www.hackerrank.com/challenges/np-shape-reshape/problem)]
Acquisisci in input una lista di 9 numeri interi, converti tale lista in un'array numpy di dimensione 3x3
<br><br>
**Esempio di input**<br>
1 2 3 4 5 6 7 8 9
<br><br>
**Esempio di output**<br>
[[1 2 3]<br>
 [4 5 6]<br>
 [7 8 9]]<br>

In [4]:
import numpy as np

# print(np.array(input().split(),int).reshape(3,3)) 
    
arr = input().split()
np_arr = np.array(arr, int)
np_arr = np_arr.reshape(3,3)

print(np_arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3. Transpose and Flatten [[Esercizio su HackerRank](https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem)]
1. Acquisci in input due numeri *N* e *M*.
2. Acquisci in input *N* righe con *M* interi e utilizzali per creare una matrice numpy.
3. Stampa la matrice trasposta.
4. Stampa la matrice flatten.

In [ ]:
import numpy as np

n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

## 4. Aritmetica degli array [[Esercizio su HackerRank](https://www.hackerrank.com/challenges/np-array-mathematics/problem)]
1. Acquisisci due numeri *N* e *M* in input
2. Acquisisci N righe di interi e utilizzale per creare la matrice numpy A
3. Acquisisci N righe di interi e utilizzale per creare la matrice numpy B
4. Stampa la somma delle matrici A e B
5. Stampa la differenza delle matrici A e B
6. Stampa il prodotto delle matrici A e B
7. Stampa la divisione tra interi tra le matrici A e B
8. Stampa il risultato del modulo tra le matrici A e B
9. Stampa il risultato della matrice A elevata la matrice B.

In [ ]:
import numpy as np

n, m = map(int, input().split())

A = np.array([input().strip().split() for _ in range(n)], int)
B = np.array([input().strip().split() for _ in range(n)], int)

print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

## 5. Funzioni statistiche [[Esercizio su HackerRank 1](https://www.hackerrank.com/challenges/np-mean-var-and-std/problem) [Esercizio su HackerRank 2](https://www.hackerrank.com/challenges/np-min-and-max/problem)]
1. Acquisisci in input due valori N e M
2. Acquisci N righe di M elementi e utilizzale per creare una matrice A
3. Stampa la media di A lungo l'asse 1
4. Stampa la varianza di A lungo l'asse 0
5. Stampa la deviazione standard di A.
6. Calcola il minimo lungo l'asse 1 e poi stampa il massimo di questo risultato.

### [Altri esercizi su HackerRank](https://www.hackerrank.com/challenges/np-arrays/problem)